name: Pull request checks

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    needs: test
    
    permissions:
      contents: read
      packages: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Set up caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/gradle/*.toml') }}
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Build the app
        run: ./gradlew assembleDebug

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Set up caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/gradle/*.toml') }}
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Lint check
        run: ./gradlew lint
      - name: Upload lint results
        uses: actions/upload-artifact@v4
        with:
          name: pr-lint-results
          path: "**/build/reports/lint-*.html"
      - name: Style check
        run: ./gradlew  --init-script gradle/spotless.gradle.kts spotlessCheck
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --stacktrace
